REG: Regexp

class Block
  @name: String
  @line: Integer
  @sigs: Array[String]
  @pure: bool
  @description: Array[String]
end

class Object
  def format_block: (Block b) -> String

  def dostuff: (String filename, String target_file) -> void
end
